/**
 * Seed a single admin from CLI. Run with:
 *   npm run seed-admin -- your@email.com 'YourPassword'
 */
import { hashPassword } from '../src/lib/auth/argon';
import { writeFileSync } from 'node:fs';

const [, , emailArg, passwordArg] = process.argv;

if (!emailArg || !passwordArg) {
  console.error('Usage: npm run seed-admin -- <email> <password>');
  process.exit(1);
}

// Validate
if (!/.+@.+\..+/.test(emailArg)) {
  console.error('Invalid email');
  process.exit(1);
}
if (passwordArg.length < 8) {
  console.error('Password must be ≥ 8 characters');
  process.exit(1);
}

const hash = await hashPassword(passwordArg);

const envBlock = `
# Generated by scripts/seed-admin.ts on ${new Date().toISOString()}
ADMIN_EMAIL=${emailArg}
ADMIN_PASSWORD_HASH=${hash}
`;

writeFileSync('.env.admin', envBlock.trim() + '\n');

console.log(`\n✅ Hashed admin password for ${emailArg}\n`);
console.log(`Add these to your .env (or Hostinger hPanel env vars):\n`);
console.log(envBlock);
console.log(`Then restart the server.\n`);